name: Gource Video Generator

on:
  workflow_dispatch:
    inputs:
      Generate_Gource_Video:
        description: 'Generate Gource history Video File'
        type: boolean
        required: false

permissions:
  contents: write

jobs:
  Generate_Gource_Video:
    name: Generate Gource History Video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Gource Video
        if: ${{ github.event.inputs.Generate_Gource_Video == 'true' }}
        run: |
          echo "Generating Gource video from API..."
          API_URL="https://api-gource.onrender.com/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          OUTPUT_FILE="gource.mp4"
          curl -L $API_URL -o $OUTPUT_FILE
          echo "✅ Gource video saved as $OUTPUT_FILE"

      - name: Commit Gource video
        if: ${{ github.event.inputs.Generate_Gource_Video == 'true' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gource.mp4
          git commit -m "Added Gource history video"
          git push
