name: Toggle variable

on:
   workflow_dispatch:
      inputs:
         Toggle_Variable:
            description: 'Toggle repo variable (true/false) using name'
            type: string
            required: false

permissions:
  contents: read
  actions: write  

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ejecutar toggle script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: python .github/scripts/toggle.py ${{ github.event.inputs.Generate_Table_Of_Contents }}
